app/blueprints/pet/__init__.py
from flask import Blueprint, render_template, flash, request, url_for, redirect
from app.models.pet import Pet
from app.models.breed import Breed
from app.forms.pet_form import PetForm
from app import db
import datetime
import timeago

bp = Blueprint('pet', __name__, template_folder='templates')

PER_PAGE = 5

@bp.route('/')
def index():
  owner_dni = request.args.get("owner_dni")
  page = request.args.get("page", 1, type=int)
  pets = Pet.query.order_by(Pet.birth_date.desc(), Pet.name.desc(), Pet.owner_name.desc()).paginate(page=page, per_page=PER_PAGE)
  owners = db.session.query(Pet.owner_name, Pet.owner_dni).distinct(Pet.owner_dni).all()

  owners_dict = [ { "owner_name": owner[0], "owner_dni": owner[1] } for owner in owners ]

  if owner_dni :
    pets = Pet.query.filter(Pet.owner_dni == owner_dni).paginate(page=page, per_page=PER_PAGE)
  
  return render_template('index.html', pets=pets, owners=owners_dict, selected_owner=owner_dni)  

@bp.route('/pet', methods=['GET', 'POST'])
def add_pet():
  pet_form = PetForm()

  if request.method == "POST" and pet_form.validate_on_submit():
    pet_data = pet_form.data
    pet_data.popitem()

    pet_object = Pet(**pet_data)

    db.session.add(pet_object)
    db.session.commit()

    flash("Se ha registrado la mascota con éxito")
    return redirect(url_for("pet.index"))

  return render_template('add_pet.html', form=pet_form)

@bp.route('/pet/<int:id>', methods=['GET'])
def detail_pet(id):
  pet_object = Pet.query.get_or_404(id)

  return render_template("detail_pet.html", pet=pet_object, timeago=timeago)

@bp.route('/pet/<int:id>/update', methods=['GET', "POST"])
def update_pet(id):
  pet_object = Pet.query.get_or_404(id)

  pet_form = PetForm()
  
  if request.method == "POST" and pet_form.validate_on_submit():
    pet_data = pet_form.data
    pet_data.popitem()

    pet_object.from_dict(**pet_data)
    pet_object.updated_at = datetime.datetime.now()
    db.session.commit()
    
    flash("Se actualizaron los datos de la mascota con éxito")

  for field in pet_form:
    if (field.name != "csrf_token"):
      field.data = getattr(pet_object, field.name)

  return render_template("update_pet.html", form=pet_form, id=id)

@bp.route('/pet/<int:id>/delete', methods=['GET'])
def delete_pet(id):
  pet_object = Pet.query.get_or_404(id)

  db.session.delete(pet_object)
  db.session.commit()

  flash("Se ha eliminado a la mascota con éxito")

  return redirect(url_for("pet.index"))

@bp.route('/breed', methods=['POST'])
def add_breed():
  name = request.form["name"]
  url_origin = request.headers.__getitem__("Referer")

  if name.__len__() > 20 or name.strip() == "" or Breed.query.filter_by(name=name).all():
    flash("Ocurrió un error al agregar la raza. Vuelve a intentarlo", "error")
    return redirect(url_origin)

  breed = Breed()
  breed.name = name

  flash("Raza añadida correctamente")

  db.session.add(breed)
  db.session.commit()

  return redirect(url_origin)

app/blueprints/pet/templates/add_pet.html
{% extends "base.html" %} {% block content %}
<h1 class="text-center">Registrar Mascota</h1>

<main>
  <div class="m-auto p-3" style="max-width: 800px">
    <form method="POST" class="mb-3 d-flex gap-3 flex-wrap">
      {{ form.csrf_token }} {% with messages =
      get_flashed_messages(with_categories=True) %} {% if messages %} {% for
      category, message in messages %}
      <div
        class="alert alert-{{ 'danger' if category == 'error' else 'success' }} w-100"
        data-message
        role="alert"
      >
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %} {% if form.errors %}
      <div class="text-danger">
        Errores:
        <ul>
          {% for field in form.errors %} {% for error in form.errors[field] %}
          <li>{{ error }}</li>
          {% endfor %} {% endfor %}
        </ul>
      </div>
      {% endif %}

      <div class="d-flex flex-wrap gap-3 w-100" style="flex-grow: 1">
        <div style="flex-grow: 1">
          <label for="name">{{ form.name.label }} </label>
          {{ form.name(placeholder="Introduce el nombre", class_="form-control")
          }}
        </div>

        <div style="flex-grow: 1">
          <label for="birth_date">{{ form.birth_date.label }} </label>
          {{ form.birth_date(placeholder="Introduce la fecha de nacimiento",
          class_="form-control") }}
        </div>
      </div>

      <div style="flex-grow: 1">
        <label for="owner_name">{{ form.owner_name.label }} </label>
        {{ form.owner_name(placeholder="Introduce el nombre del propietario",
        class_="form-control") }}
      </div>

      <div style="flex-grow: 1">
        <label for="owner_dni">{{ form.owner_dni.label }} </label>
        {{ form.owner_dni(placeholder="Introduce el dni del propietario",
        class_="form-control") }}
      </div>

      <div class="w-100 d-flex flex-wrap gap-3" style="flex-grow: 1">
        <div style="flex-grow: 5">
          <label for="breed">{{ form.breed.label }} </label>
          {{ form.breed(class_="form-select") }}
        </div>

        <a
          id="btn-add-breed"
          class="btn btn-light align-self-end"
          style="flex-grow: 1"
          >Añadir Raza</a
        >
      </div>

      <div class="w-100 text-center">
        <input
          class="btn btn-primary align-self-start w-100"
          style="max-width: 250px"
          type="submit"
          value="Registrar"
        />
      </div>
    </form>

    <a href="/">⏪ Volver al inicio</a>
  </div>
</main>

{% endblock %} {% block scripts %}
<script src="../../../static/add_pet.js" type="module"></script>
{% endblock %}

app/blueprints/pet/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Globalvet</title>
    <link rel="icon" type="image/x-icon" href="../../../static/img/logo.png" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../../../static/style.css" />
  </head>
  <body class="min-vh-100 d-flex justify-content-center align-items-center">
    <div class="m-3">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

app/blueprints/pet/templates/detail_pet.html
{% extends "base.html" %} {% block content %}
<h1 class="text-center">Detalle de Mascota</h1>

<main>
  <div class="m-auto p-3" style="max-width: 600px">
    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Nombre:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4">{{ pet.name }}</span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Fecha de nacimiento:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4">{{ pet.birth_date }}</span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Raza:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4"> {{ pet.breed.name }} </span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end text-center">Nombre del propietario:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4"> {{ pet.owner_name }} </span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Dni del propietario:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4"> {{ pet.owner_dni }} </span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Creado hace:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4">
          {{ timeago.format(date=pet.created_at, locale="es").capitalize() }}
        </span>
      </div>
    </div>

    <div class="d-flex flex-wrap justify-content-center gap-3 mb-2">
      <h3 class="m-0 align-self-end">Actualizado hace:</h3>
      <div class="border-bottom border-1 text-center" style="flex-grow: 1">
        <span class="fs-4">
          {{timeago.format(date=pet.updated_at, locale="es").capitalize() if
          pet.updated_at else 'Sin actualizar' }}
        </span>
      </div>
    </div>

    <div
      class="d-flex flex-wrap gap-3 my-3 mx-auto px-3"
      style="max-width: 500px"
    >
      <a
        style="flex-grow: 1"
        class="btn btn-warning"
        href="{{ url_for('pet.update_pet', id=pet.id) }}"
        >Editar</a
      >
      <a style="flex-grow: 1" class="btn btn-danger" data-delete-id="{{pet.id}}"
        >Eliminar</a
      >
    </div>

    <a href="/">⏪ Volver al inicio</a>
  </div>
</main>
{% endblock %} {% block scripts %}
<script src="../../../static/detail_or_updated_pet.js" type="module"></script>
{% endblock %}

app/blueprints/pet/templates/index.html
{% extends "base.html" %} {% block content %}
<h1 class="text-center">Listado de Mascotas</h1>

<form method="GET" class="m-auto p-3 d-flex justify-content-end flex-wrap gap-3" style="max-width: 600px;">
  <div class="d-flex flex-column" style="flex-grow: 2;">
    <label for="owner_dni">Seleccionar cliente: </label>
    <select id="owner_dni" class="form-select" name="owner_dni">
      <option value="">-- Todos ---</option>
      {% for owner in owners %}
      <option value="{{ owner.owner_dni }}" {% if owner.owner_dni == selected_owner %} selected {% endif %}>{{ owner.owner_name }}</option>
      {% endfor %}
    </select>
  </div>

  <input class="btn btn-primary align-self-end" style="flex-grow: 1;" type="submit" value="Filtrar" />

  <a class="btn btn-success align-self-end" style="flex-grow: 1;" href="/pet">Registrar Mascota</a>

  <a id="btn-add-breed" class="btn btn-light align-self-end" style="flex-grow: 1;">Añadir Raza</a>
</form>

<main>
  <div class="p-3">
    {% with messages =
      get_flashed_messages(with_categories=True) %} {% if messages %} {% for
      category, message in messages %}
      <div
        class="alert alert-{{ 'danger' if category == 'error' else 'success' }} w-100"
        data-message
        role="alert"
      >
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %}
    <table class="table text-center m-auto" style="max-width: 1200px;">
      <caption>Lisa de Mascotas</caption>
      <thead class="align-middle">
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Fecha de nacimiento</th>
          <th scope="col">Raza</th>
          <th scope="col">Nombre del propietario</th>
          <th scope="col">Dni del propietario</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody class="table-group-divider align-middle">
        {% if not pets.items %}
          <tr>
            <td class="no-data" colspan="8">No hay datos</td>
          </tr>
        {% else %}
          {% for pet in pets %}
            <tr id="pet-{{ pet.id }}">
              <td data-label="Nombre">{{ pet.name }}</td>
              <td data-label="Fecha de nacimiento">{{ pet.birth_date }}</td>
              <td data-label="Raza">{{ pet.breed.name }}</td>
              <td data-label="Nombre del propietario">{{ pet.owner_name }}</td>
              <td data-label="Dni del propietario">{{ pet.owner_dni }}</td>
              <td data-label="Acciones">
                <div class="d-flex flex-wrap gap-1">
                  <a style="flex-grow: 1;" class="btn btn-primary" href="{{ url_for('pet.detail_pet', id=pet.id) }}" >Más detalles</a>
                  <a style="flex-grow: 1;" class="btn btn-warning" href="{{ url_for('pet.update_pet', id=pet.id) }}" >Editar</a>
                  <a style="flex-grow: 1;" class="btn btn-danger" data-delete-id="{{pet.id}}">Eliminar</a>
                </div>
              </td>
            </tr>
          {% endfor %}
        {% endif %}
      </tbody>
    </table>
    
    {% if pets.items %}
      <nav>
        <ul class="pagination pagination-sm flex-wrap justify-content-center m-0">
          {% if pets.has_prev %}
              <li class="page-item">
                <a class="page-link" href="{{ url_for('pet.index', page=pets.prev_num, owner_dni=selected_owner) }}">Retroceder</a>
              </li>
          {% else %}
              <li class="page-item disabled">
                <span class="page-link">Retroceder</span>
              </li>
          {% endif %}

          {% for number in pets.iter_pages() %}
              {% if number %}
                {% if pets.page != number %}
                    <li class="page-item">
                      <a class="page-link"  href="{{ url_for('pet.index', page=number) }}">{{ number }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                      <a class="page-link">{{ number }}</a>
                    </li>
                {% endif %}
              {% endif %}
          {% endfor %}

          {% if pets.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ url_for('pet.index', page=pets.next_num, owner_dni=selected_owner) }}">Avanzar</a>
              </li>
          {% else %}
              <li class="page-item disabled">
                <span class="page-link">Avanzar</span>
              </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
</main>
{% endblock %}

{% block scripts %}
<script src="../../../static/index.js" type="module"></script>
{% endblock %}

app/blueprints/pet/templates/update_pet.html
{% extends "base.html" %} {% block content %}
<h1 class="text-center">Actualizar Mascota</h1>

<main>
  <div class="m-auto p-3" style="max-width: 800px">
    <form method="POST" class="mb-3 d-flex gap-3 flex-wrap">
      {{ form.csrf_token }} {% with messages =
      get_flashed_messages(with_categories=True) %} {% if messages %} {% for
      category, message in messages %}
      <div
        class="alert alert-{{ 'danger' if category == 'error' else 'success' }} w-100"
        data-message
        role="alert"
      >
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %} {% if form.errors %}
      <div class="text-danger">
        Errores:
        <ul>
          {% for field in form.errors %} {% for error in form.errors[field] %}
          <li>{{ error }}</li>
          {% endfor %} {% endfor %}
        </ul>
      </div>
      {% endif %}

      <div class="d-flex flex-wrap gap-3 w-100" style="flex-grow: 1">
        <div style="flex-grow: 1">
          <label for="name">{{ form.name.label }} </label>
          {{ form.name(placeholder="Introduce el nombre", class_="form-control")
          }}
        </div>

        <div style="flex-grow: 1">
          <label for="birth_date">{{ form.birth_date.label }} </label>
          {{ form.birth_date(placeholder="Introduce la fecha de nacimiento",
          class_="form-control") }}
        </div>
      </div>

      <div style="flex-grow: 1">
        <label for="owner_name">{{ form.owner_name.label }} </label>
        {{ form.owner_name(placeholder="Introduce el nombre del propietario",
        class_="form-control") }}
      </div>

      <div style="flex-grow: 1">
        <label for="owner_dni">{{ form.owner_dni.label }} </label>
        {{ form.owner_dni(placeholder="Introduce el dni del propietario",
        class_="form-control") }}
      </div>

      <div class="w-100 d-flex flex-wrap gap-3" style="flex-grow: 1">
        <div style="flex-grow: 5">
          <label for="breed">{{ form.breed.label }} </label>
          {{ form.breed(class_="form-select") }}
        </div>

        <a
          id="btn-add-breed"
          class="btn btn-light align-self-end"
          style="flex-grow: 1"
          >Añadir Raza</a
        >
      </div>

      <div
        class="w-100 text-center d-flex flex-wrap justify-content-center gap-3"
      >
        <input
          class="btn btn-warning align-self-start"
          style="max-width: 250px; flex-grow: 1"
          type="submit"
          value="Actualizar"
        />

        <a
          class="btn btn-danger align-self-start"
          style="max-width: 250px; flex-grow: 1"
          data-delete-id="{{id}}"
        >
          Eliminar
        </a>
      </div>
    </form>

    <a href="/">⏪ Volver al inicio</a>
  </div>
</main>
{% endblock %} {% block scripts %}
<script src="../../../static/detail_or_updated_pet.js" type="module"></script>
{% endblock %}